services:
  - type: web
    name: counter-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: GENERATE_SOURCEMAP
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
